### ISSUE TITLE
Enable dependabot

### ISSUE THREAD

**Issue by olblak** [epinio/epinio#1025]
**Is your feature request related to a problem? Please describe.**

It's easier to integrate dependency upgrades on a regular basis than once every age.
The Epinio project could easily benefit from the integration with Dependabot 
-> https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates.

**Describe the solution you'd like**

We could drop the file `dependabot.yaml` in the directory `.github` with the following content

```
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
```

Dependabot would then check once a week if some dependency updates are available

**Describe alternatives you've considered**
While other tools can be used like Renovatebot, Dependabot is already well integrated with Github

**Additional context**
