### ISSUE TITLE
Application restart endpoint

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#1074]
This is a follow up of this story: https://github.com/epinio/ui/issues/10

Sometimes, users want to restart applications. This can happen for various reasons (e.g. flush logs, expire caches, quickly fix problems like memory leaks before a code fix is in place, etc). 

Epinio currently doesn't have a way to simply restart an application. We need to implement an endpoint that will do something like the equivalent of this command on the app deployment: 

```kubectl rollout restart deployment app_deployment_here```

**Comment by thardeck** [comment]
It seems that the best way to restart an app would be to use the patch deployment function and add a dummy annotation to the spec.template.metadata.annotations block. This should trigger the creation of a new replicaset and automatically handle the restart based on the strategy specified in the deployment spec.
That is also what kubectl rollout restart deployment does behind the scenes.
When you run kubectl rollout restart deployment, it adds a kubectl.kubernetes.io/restartedAt annotation which contains a timestamp, like this one:

```
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2021-02-15T11:12:54-05:00"
```
