### ISSUE TITLE
Unable to re-stage when previous staging failed

### ISSUE THREAD

**Issue by andreas-kupries** [epinio/epinio#1179]
The current logic for the application state does not work correctly for the new job-based stager and prevents re-staging when a previous staging run failed. It claims that this failed staging run is still active.

Edit: Folding https://github.com/epinio/epinio/pull/1141#pullrequestreview-871446865 into here also.

> Look into using `Job` states for staged detection, and possible failure, instead of `Pod` state.

Edit: How useful would `k8s.io/kubectl/pkg/util/podutils` be ? Is there something similar for jobs too ?

**Comment by andreas-kupries** [comment]
Results of current behaviour:

good staging
```
status:
  completionTime: "2022-02-03T10:44:57Z"
  conditions:
  - lastProbeTime: "2022-02-03T10:44:57Z"
    lastTransitionTime: "2022-02-03T10:44:57Z"
    status: "True"
    type: Complete
  startTime: "2022-02-03T10:42:50Z"
  succeeded: 1
```

failed staging
```
status:
  active: 1
  startTime: "2022-02-03T11:42:21Z"
```

Note how the failed pod does not reflect in the job.

I am currently wondering if the `curl` should be moved into a trap command.
I.e. always execute on exit, even if we abort much earlier.
I.e. if the active sidecar prevents the pod from properly exiting/completing, and that this prevents reflection of the state up into the job.
