### ISSUE TITLE
Fix secretName in application Chart

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#1341]
Some specific names can cause this problem when the application is created:

```
 Invalid value: \"i-apps-11003950-apps-11003950.-f8970e588d3f224a898c054ae7f002f\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')" "requestId"= "f1031de0-6cf4-4a8b-a881-f8b17982ad1a" "origin"="/api/v1/namespaces/namespace-207853377/applications/apps-11003950/deploy" "error"="release apps-11003950 failed, and has been uninstalled due to atomic being set
```

The reason is [how we construct the `secretName`](https://github.com/epinio/helm-charts/blob/main/chart/application/templates/ingress.yaml#L45).  The part that makes it break is the `.-`. Removing the `-` makes it work. 

Relevant helper here: https://github.com/epinio/helm-charts/blob/main/chart/application/templates/_helpers.tpl#L32

Suggestion from @andreas-kupries on Slack: 

```
maybe remove the - from the truncate and make the sha256 piece larger (i.e. 32).
```

Test yaml:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: epinio2
  namespace: epinio
spec:
  rules:
  - host: epinio2.192.168.48.3.omg.howdoi.website
    http:
      paths:
      - backend:
          service:
            name: epinio-ui
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - epinio.192.168.48.3.omg.howdoi.website
    secretName: i-apps-11003950-apps-11003950.-f8970e588d3f224a898c054ae7f002f
```
(fails to apply, remove the `-` from `.-` and it works)
