### ISSUE TITLE
epinio service create and then bind success for 1st time. subsequent creation, the cred is incorrect

### ISSUE THREAD

**Issue by gitricko** [epinio/epinio#1386]
**Describe the bug**
If you create a service via catalog (either postgres or rabbitmq) and later bind to an app. App shall able to communicate with it using the creds in the files in configuration folder.
If you undeploy the app and also the services.... and redo it again. The subsequent time, the app shall complain that the creds is invalid!

In order to fix it, you need to tear down epinio and rebuild/reinstall again.

**To Reproduce**
Steps to reproduce the behavior, e.g.:

1. push and app
2. create services via service create
3. service bind app
4. the app shall be able to use the creds
5. delete app and services
6. redo 1 - 3
7. Now the app is not able to use the cred created in the configuration folder

**Expected behavior**
- Above step should work

**Logs**
The application logs on the 2nd run... it will just complain the creds is invalid. My app have both rabbitmq and postgres. It took me a long time to figure out why.

You can increase Epinio's logging by exporting these variables:

```
export TRACE_LEVEL=255
export DEBUG=true
```

To follow the server logs you can use:

`kubectl logs -n epinio -l app.kubernetes.io/name=epinio-server -c epinio-server -f`

**Cluster (please complete the following information):**
 - Provider: K3D

**Desktop/CLI (please complete the following information):**
 - OS: Linux, 
 - Epinio Version: 0.7.1

**Additional context**
I am using the installer from here.
https://gist.github.com/gitricko/b5125a3649e5d52faec4e4f9a496e166

**Comment by enrichman** [comment]
Hi @gitricko, sorry for the late reply. I've tried and I was able to reproduce the issue.

The problem is related to the old PVCs still hanging around. Basically, after the deletion of the Postgres the Volume with the old data is still in the cluster (with the old password), and recreating a new DB with the same name will reuse the same data (if you try to login with the old password it will work).

This seems a [common issue](https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues) with the Bitnami charts, and also the removal of the PVCs with the `helm uninstall` is under review, and it will [_maybe_ added in version 4](https://github.com/helm/helm/issues/5156#issuecomment-833869431).

So as a quick fix, after the deletion of your service, you can just delete manually its PVCs, using a label selector for your service

```
kubectl delete pvc -n <NAMESPACE> -l app.kubernetes.io/instance=<NAMESPACE>-<SERVICENAME>
```

or even all the PVCs in the namespace (if you have multiple services and you don't care about anything else)

```
kubectl delete pvc -n <NAMESPACE> --all
```

Since these are supposed to be services just for testing purposes probably it would make sense to have a fixed username and password, as the one that we have in our [sample](https://github.com/epinio/application/blob/main/config/samples/application_v1_service.yaml).

**Comment by jimmykarily** [comment]
If there is a guaranteed way to tell what PVCs where created by the service helm chart, we should delete them (since helm doesn't). If not, we should either wait until [helm supports that](https://github.com/helm/helm/issues/5156#issuecomment-833869431) or we can have better helm charts in the future that have [a "post-delete" hook to do the cleanup](https://helm.sh/docs/topics/charts_hooks/).

Let's do some more research

**Comment by jimmykarily** [comment]
There doesn't seem to be a way to identify pvcs that belong to the just-removed helm release. On the other hand, helm hooks are easy to implement. I just put the following yaml in the `templates` directory of the bitnami mysql chart and it does the job:

```
# Post-delete hook to delete PVCs after `helm uninstall`
# Until helm supports it: https://github.com/helm/helm/issues/5156
{{- if and .Values.primary.persistence.enabled (not .Values.primary.persistence.existingClaim) }}

# Create a service account, role and binding to allow to list, get and
# delete PVCs. It should be used by the job below.

# To ensure the resources are deleted, use this annotation:
#
# annotations:
#  "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded

# https://helm.sh/docs/topics/charts_hooks/#hook-resources-are-not-managed-with-corresponding-releases
# https://helm.sh/docs/topics/charts_hooks/#hook-deletion-policies

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pvc-deleter
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-6"

---
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
kind: Role
metadata:
  name: pvc-deleter
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-6"
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - delete
      - list

---
kind: RoleBinding
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
metadata:
  name: pvc-deleter
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-5"
subjects:
  - kind: ServiceAccount
    name: pvc-deleter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pvc-deleter

---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      serviceAccountName: pvc-deleter
      containers:
      - name: post-install-job
        image: "bitnami/kubectl"
        command: ["kubectl", "delete", "pvc", "-n", "{{ .Release.Namespace }}", "-l", "app.kubernetes.io/instance={{ .Release.Name }}"]
{{- end }}
```

It would need some more work to give the serviceaccount a more "random" name but this at least proves it's possible. The post-delete hook job fires up when `helm uninstall` is done and deletes the pvc.

I see 3 options:

1. We fork the bitnami charts and we add the hooks we need in our fork.
2. We upstream this (with some flag to enable the cleanup through `values.yaml` ?)
3. We just document this and we leave our "demo" services as they are. We will simply tell people how to create their own charts that work better than ours.

In my opinion, we should try #2 and if that fails go with #1. Opinions?
