### ISSUE TITLE
[Spike] Allow Epinio users to login with any OIDC provider

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#1571]
Relevant: https://github.com/epinio/epinio/issues/686

We ran a spike around a year ago (see link above). Let's check if there are other alternatives and how the previous findings would work with the current Epinio. There [is a branch](https://github.com/epinio/epinio/tree/486-multiple-users-dex) which should have a working PoC of the old Spike.

## What we need

- Users should be able to login to Epinio using existing accounts on some OIDC provider (GitHub, Google, etc)
- Operators should be able to enable/disable OIDC providers
- If there is any authz information provided by the upstream provider, see if we can make any use of it (e.g. to replace our namespace based authz).
- In any case, operators should be able to promote users to admins or revoke admin rights.

**Comment by gitricko** [comment]
I will up vote this ! Cos we need something like this for production use

**Comment by pedroh4659** [comment]
@jimmykarily I think this is a great feature to have, do you have more information about which OIDC are first on list?

Also, a suggestion on improving the Epinio authentication: Supporting personal access tokens on the Epinio CLI would allow users to deploy an Epinio instance behind a third-party SSO such as [Authelia](https://www.authelia.com/) or [Authentik](https://goauthentik.io/). A good example is [how Gitlab uses tokens](https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html) as an alternative to Oauth2.

**Comment by jimmykarily** [comment]
@pedroh4659 the idea currently is to try to use some "proxy" like [dex](https://dexidp.io/) to allow operators to enable various identity providers (see a list [here](https://dexidp.io/docs/connectors/)). We need to look deeper into Authelia and Authentic docs but my quick guess is that they could be used with dex too if they implement one of the supported protocols. I don't know much about those projects though so I could be completely off here. That's why we do this Spike after all.

Thanks for sharing those links and for you suggestions. It's important to pick a solution that works for most people and doesn't require custom code for every single identity provider.

**Comment by andreas-kupries** [comment]
More notes

# Spike Dex

  1. Deploy Dex helm chart as sub chart of epinio.
     Is the version still 0.5, a year later  ?
     Translate the old values.yaml for that.

  2. epinio server's router needs a new middleware stage directing the initial basic-auth requests to dex.

     Dex creates the token ...

     Need the new endpoints again ?

  3. Token validation also done by dex ?

     I.e. redirecting token auth to dex as well ?

  4. Fallback to the old user auth (secrets) for default setup ?

     Or full removal of non-dex auth ?

# Dex Alternatives

??

**Comment by andreas-kupries** [comment]
# Details from the old spike

|What|Where|
|---|---|
|Sources|https://github.com/dexidp/dex|
|Chart src|https://github.com/dexidp/helm-charts|
|Repo|`helm repo add dex https://charts.dexidp.io`<br>`helm search repo dex`|
|Current|chart `0.9.0` for dex `2.32.0`|
|Previous|chart `0.5.0` for dex `2.29.0`|
|DexDeploymentID|"dex"|
|Deploy|`helm update dex --values <config.yaml> --namespace dex <tarpath>`|

config.yaml -- See https://github.com/dexidp/dex/blob/master/config.yaml.dist for current
Becomes helm `--values` file.

Below the file as generated by the old spike, using `{{...}}` notation for the placeholders filled by `fmt.Sprintf`.

```
issuer: https://{{ DexDeploymentID+"."+domain }}
https:
  port: 5554
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: {{ issuer }}
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: {{ DexDeploymentID+"."+domain }}
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - {{ DexDeploymentID+"."+domain }}
      secretName: dex-cert

config:
  # TODO: What should this be?
  issuer: https://{{ DexDeploymentID+"."+domain }}
  storage:
    type: kubernetes
    config:
      inCluster: true
  web:
    http: {{ DexDeploymentID+"."+domain }}
  enablePasswordDB: true
  # TODO: Templatize and generate this
  staticPasswords:
    - email: "admin@example.com"
      hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
      username: "admin"
      userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
  staticClients:
   - id: epinio
      secret: {{ --- "123", // TODO: Generate and store the secret somewhere }}
      name: 'Epinio'
      # Where the app will be running.
      redirectURIs:
      - '{{ "https://auth.10.86.4.38.omg.howdoi.website/_oauth", // TODO: DRY this? (with the forward auth installation) }}'
```

Notes, comparing to newest https://github.com/dexidp/dex/blob/master/config.yaml.dist
There was a bit of confusion ...

  - `ingress` seems to be gone
  - `config` seems to be gone, children moved one level up into toplevel

None of this is true. Looking at README.md and values.yaml of the latest chart it becomes clear that the `config.yaml.dist` is just the data for the `config` key of values.yaml. The config from the old spike is for the entire values.yam, thus has `config` and ingress` keys.
