### ISSUE TITLE
Allow setting service chart values with CLI

### ISSUE THREAD

**Issue by braunsonm** [epinio/epinio#1633]
**Is your feature request related to a problem? Please describe.**
I would like to be able to set the underlying helm chart values of a service per instance using the CLI. This would allow me to configure say, a different DB size for a specific app that needs a service of that size.

**Describe the solution you'd like**
Expansion to the `epinio service create` to allow passing in a values file. Potentially with some templating from epinio for the service name etc.

**Describe alternatives you've considered**
The only alternative I can think of is having a different custom service with pre-made settings for every possible combination.

**Additional context**
I could be missing something but I don't see this as being possible under the CLI here: https://docs.epinio.io/references/cli/epinio_service_create

Side question... is it not possible for these configuration values after the bind to be exposed as environment variables? From what I can tell they are just mounted according to this: https://docs.epinio.io/references/configurations

**Comment by enrichman** [comment]
Hi @braunsonm, thanks. This is something we thought about, but we left for a future release since it has some consideration to think about. For example it will be awesome for the developer to provide a DB with different sizes or configuration, but should we think about restricting those values? Can a developer create a DB with any custom values or should we restrict them in ranges/whitelists in order to avoid errors and increase security?

**Comment by braunsonm** [comment]
@enrichman these are good questions and now that you mention it, I would like to be able to restrict it. For instance I don't want any ingress or load balancer resources to be created that might open security holes in the cluster.

**Comment by jimmykarily** [comment]
@braunsonm we've discussed that in the past and the team felt that a different plan for each set of configuration options makes more sense for a markeplace (same solution as the one you suggest as an "alternative you've considered"). Many marketplaces work like that. Is there any use case in which this would not work or would feel weird?

The alternative can become very complex and insecure. For example, not only do we need a whitelist (e.g. only allow changing the size of the database)  but also allowed ranges (e.g. users can change the size of the database but can't go beyong 10Tb etc) or even just allow specific values. In cases like that, a different plan for each configuration makes more sense imho.

**Comment by braunsonm** [comment]
I can see how that would be difficult but it's also hard to guess what all the possible options a user would want. For example a user might want to change their logging or auth settings which can only be done in the chart values.

It's true this is a hard problem and I don't have a great solution for you. Perhaps we need to manage this ourselves outside of Epinio with GitOps

**Comment by jimmykarily** [comment]
Let's keep this issue open to give it a try. We have [a similar issue](https://github.com/epinio/epinio/issues/1252) open for the application chart. Maybe the solution can work for both (e.g. a yaml based "DSL" to define what is accessible and configurable from a helm chart's values.yaml file).

**Comment by richard-cox** [comment]
GH issue for UI parts - https://github.com/epinio/ui/issues/252

**Comment by thehejik** [comment]
**Report**
E deployed from helm branch `1633-service-custom-values`
E server and CLI build and patched from branch `1633-service-custom-values`

**Current limitations**
- list of strings as a value are not supported - this can be useful esp. for `annotations`
- Command `epinio-service service show mysql` for inspecting deployed service doesn't display used setting values

**Testing**
1) existing mysql-dev service catalog modified by `kubectl edit services.application.epinio.io -n epinio mysql-dev` command, the following appended at the same level as `values`:
```yaml
  settings:      
    auth.rootPassword:                           
      type: string                                                       
    primary.persistence.size:                                                     
      type: string                                                 
    primary.persistence.enabled:                                       
      type: bool                                                       
    primary.persistence.annotations:                                         
      type: string                                                                
      enum:                                                                   
      - "first"                                                               
      - "second"                                                              
      - "third"                                                               
    primary.service.annotations:                                              
      type: integer                                                    
      minimum: '1024'                                                       
      maximum: '2048'
```
2) verification of the new Settings `$ epinio service catalog mysql-dev`:
```
...
🚢  Settings
|               KEY               |  TYPE   |    ALLOWED VALUES    |
|---------------------------------|---------|----------------------|
| auth.rootPassword               | string  |                      |
| primary.persistence.annotations | string  | first, second, third |
| primary.persistence.enabled     | bool    |                      |
| primary.persistence.size        | string  |                      |
| primary.service.annotations     | integer | [1024 ... 2048]      |
```
3) validation of the allowed values and types:
* integer out of bounds: `-v primary.service.annotations=1`
```
❌  error creating service: service create failed: Bad Request: Setting "primary.service.annotations": Out of bounds, "1" too small
```
* wrong boolean value: `-v primary.persistence.enabled=truegh`
```
❌  error creating service: service create failed: Bad Request: Setting "primary.persistence.enabled": Expected boolean, got "truegh"
```
* unavailalbe enum value: `-v primary.persistence.annotations=fr`
```
❌  error creating service: service create failed: Bad Request: Setting "primary.persistence.annotations": Illegal string "fr"
```
4) service deployment with expected values (unable to use list of strings so skipping annotations):
```
$ epinio service create mysql-dev mysql -v auth.rootPassword=linux -v primary.persistence.enabled=true -v primary.persistence.size=2Gi
```
5) the defined values are set in mysql service:
- mysql PV is 2Gi (8Gi default)
- `mysql -u root -p` in the pod accepts `linux` as a password

6) the new flag for settings chart-values is present in help:
```
$ epinio service create --help
Create a service SERVICENAME of an Epinio catalog service CATALOGSERVICENAME

Usage:
  epinio service create CATALOGSERVICENAME SERVICENAME [flags]

Flags:
  -v, --chart-value strings   chart customization to be used
  -h, --help                  help for create
      --wait                  Wait for deployment to complete
...
```
