### ISSUE TITLE
Username with `@` fails when deploying an app

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#1679]
**Describe the bug**
A user having a username with special characters (i.e.: `@`) fails when deploying an application.

This is because the username is used in labels in some resources.

**To Reproduce**
1. Create a user with username `admin@example.com`
2. Login
3. Deploy an app

**Expected behavior**
He should be able to deploy.

**Logs**
```
❌  error pushing app to server: can't deploy app: Internal Server Error: release sample-8151325dcdbae9e0ff95f9f9658432dbedfdb209 failed, and has been uninstalled due to atomic being set: Service "rsample-8151325dcdbae9e0ff95f9f9658432dbedfdb209" is invalid: metadata.labels: Invalid value: "admin@example.com": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

**Comment by mmartin24** [comment]
Did a quick check and seems to work in the CLI but not in the UI:

CLI: 
```
➜  ~ helm upgrade --install epinio -n epinio --create-namespace epinio/epinio --set global.domain=172.19.0.3.omg.howdoi.website --set global.tlsIssuer=letsencrypt-epinio  --values newusers.yaml

Release "epinio" has been upgraded. Happy Helming!
NAME: epinio
LAST DEPLOYED: Thu Aug 25 10:39:06 2022
NAMESPACE: epinio
STATUS: deployed
REVISION: 3
TEST SUITE: None
NOTES:
To interact with your Epinio installation download the latest epinio binary from https://github.com/epinio/epinio/releases/latest.

Login to the cluster with any of

    `epinio login -u admin https://epinio.172.19.0.3.omg.howdoi.website/`
    `epinio login -u admin@example.com https://epinio.172.19.0.3.omg.howdoi.website/`

or go to the dashboard at: https://epinio.172.19.0.3.omg.howdoi.website/

If you didn't specify a password the default one is `password`.

For more information about Epinio, feel free to checkout https://epinio.io/ and https://docs.epinio.io/.
➜  ~ epinio login -u admin@example.com https://epinio.172.19.0.3.omg.howdoi.website/

🚢  Login to your Epinio cluster [https://epinio.172.19.0.3.omg.howdoi.website/]
Password: 

⚠️  Certificate signed by unknown authority

|     KEY     |      VALUE       |
|-------------|------------------|
| Issuer Name | CN=epinio-ca     |
| Common Name | epinio-ca        |
| Expiry      | 2022-November-23 |

Do you want to trust it (y/n): y

✔️  Trusting certificate...

✔️  Login successful
```

UI: 
![image](https://user-images.githubusercontent.com/37271841/186625386-26dcd4f1-7e59-4b8c-b4f9-6bb5e16e016f.png)

`newusers.yaml` file used:

```
api:
  # Default users
  users:
    - username: admin
      passwordBcrypt: "$2a$10$6bCi5NMstMK781In7JGiL.B44pgoplUb330FQvm6mVXMppbXBPiXS"
      role: admin
    - username: admin@example.com
      passwordBcrypt: "$2a$10$6bCi5NMstMK781In7JGiL.B44pgoplUb330FQvm6mVXMppbXBPiXS"
      role: admin
      workspaces:
        - workspace
```

**Comment by mmartin24** [comment]
A couple of extra notes:

1. Creating users with `numbers` (11111) or `numbers in a string` ("111111") will not work.
2. Quotes are not escaped from if included in user

For case 1 and  **numbers in string** I get:

Yaml:
```
api:
  # Default users
  users:
      #user1 password: Hell@World
    - username: "111111"
      passwordBcrypt: "$2y$10$xrZYXonrAnklLCURDX2zu.HacO02Fflp5toM/riJ028aNS2PJRutS"
      role: user
      workspaces:
        - workspace
```
error:
```
Error: UPGRADE FAILED: failed to create resource: Secret in version "v1" cannot be handled as a Secret: v1.Secret.StringData: ReadString: expects " or n, but found 1, error found in #10 byte of ...|sername":111111},"ty|..., bigger context ...|X2zu.HacO02Fflp5toM/riJ028aNS2PJRutS","username":111111},"type":"BasicAuth"}
```

For case 1 witth **numbers** only (no strings):

Yaml:
```
api:
  # Default users
  users:
      #user1 password: Hell@World
    - username: 111111
      passwordBcrypt: "$2y$10$xrZYXonrAnklLCURDX2zu.HacO02Fflp5toM/riJ028aNS2PJRutS"
      role: user
      workspaces:
        - workspace

```

Error:
```
Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
epinio:
- api.users.0.username: Invalid type. Expected: string, given: integer
```
I am guessing the error is correct here.


For case 2 (quotes):

Yaml:
```
api:
  # Default users
  users:
      #user2 password: Hell@World
    - username: user"$ 
      passwordBcrypt: "$2y$10$I3/6py4jE4.P5IO1lWKg5e7D3.WQ8JKPX0kHTgPQPjW/h59utwzo6"
      role: user
      workspaces:
        - workspace
```
Login seems to be ok but when using the suggested login command it does not work (it displays a `dquote` on next line):
```
To interact with your Epinio installation download the latest epinio binary from https://github.com/epinio/epinio/releases/latest.

Login to the cluster with any of

    `epinio login -u user"$ https://epinio.172.19.0.3.omg.howdoi.website`

or go to the dashboard at: https://epinio.172.19.0.3.omg.howdoi.website

If you didn't specify a password the default one is `password`.

For more information about Epinio, feel free to checkout https://epinio.io/ and https://docs.epinio.io/.
➜  ~ epinio login -u user"$ https://epinio.172.19.0.3.omg.howdoi.website
dquote> 


```
