### ISSUE TITLE
MongoDB as one of the default dev backing service in Epinio

### ISSUE THREAD

**Issue by gitricko** [epinio/epinio#1688]
**Is your feature request related to a problem? Please describe.**
How about having MongoDB as one of the default service catalog ?

**Describe the solution you'd like**
As a developer, i would like to have mongodb as backing service too

**Describe alternatives you've considered**
Manual install can be done via add this file.

mongdb-service.yaml
```
---
apiVersion: application.epinio.io/v1
kind: Service
metadata:
  name: mongo-dev
spec:
  name: mongo-dev
  shortDescription: |
    A MongoDB service that can be used during development
  description: |
    This service is going to deploy a simple default Bitnami MongoDB instance.
    You can find more info at https://github.com/bitnami/charts/tree/master/bitnami/mongodb/.
    This database is running inside the cluster so it's probably not a good choice for production
    environments, at least with this default configuration.
  chart: mongodb
  helmRepo:
    name: bitnami
    url: "https://charts.bitnami.com/bitnami"
  values: |
    auth:
      enabled: true
```

and then run this command:

```
kubectl apply -n epinio -f  mongdb-service.yaml
```

**Additional context**
NA
