### ISSUE TITLE
Username with numbers only will fail to login

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio#1728]
Related issue: https://github.com/epinio/epinio/issues/1679

Adding an user with just numbers as string will not work for login. Checked on `v1.1.0-90-g4d2b0281`

I used this configuration for creating the user in the `yaml` file:

```
api:
  # Default users
  users:
    #password: admin
    - username: "111111"
      passwordBcrypt: "$2a$10$6bCi5NMstMK781In7JGiL.B44pgoplUb330FQvm6mVXMppbXBPiXS"
      role: user
      workspaces:
        - workspace
```

**Result:**

```
➜  epinio git:(main) ✗ helm upgrade --install epinio -n epinio --create-namespace epinio/epinio --set global.domain=172.19.0.3.omg.howdoi.website --set global.tlsIssuer=letsencrypt-epinio  --values /home/mmartin/newusers.yaml
Error: UPGRADE FAILED: failed to create resource: Secret in version "v1" cannot be handled as a Secret: v1.Secret.StringData: ReadString: expects " or n, but found 1, error found in #10 byte of ...|sername":111111},"ty|..., bigger context ...|JGiL.B44pgoplUb330FQvm6mVXMppbXBPiXS","username":111111},"type":"BasicAuth"}
```

**Comment by andreas-kupries** [comment]
I suspect the issue is missing forced quoting in the epinio helm chart. Specifically at

https://github.com/epinio/helm-charts/blob/7d5a55aa73e6664fe9e0c8ac8813a3dea40999ba/chart/epinio/templates/default-user.yaml#L13-L14

Will test this hypothesis now.

**Comment by andreas-kupries** [comment]
Confirmed, adding `| quote` fixes the install/upgrade, and `epinio login` works.

PR to come.

**Comment by andreas-kupries** [comment]
Fix PR: https://github.com/epinio/helm-charts/pull/289
Import: https://github.com/epinio/epinio/pull/1800

**Comment by mmartin24** [comment]
I checked the following:

**Scenario 1: Login in CLI with "11111" and 11111 with username `"11111"`** 
```yaml
users:
    - username: admin
      passwordBcrypt: "$2a$10$6bCi5NMstMK781In7JGiL.B44pgoplUb330FQvm6mVXMppbXBPiXS"
      role: admin
    - username: epinio
      passwordBcrypt: "$2a$10$6bCi5NMstMK781In7JGiL.B44pgoplUb330FQvm6mVXMppbXBPiXS"
      role: user
    - username: "11111"
      passwordBcrypt: "$2a$10$6bCi5NMstMK781In7JGiL.B44pgoplUb330FQvm6mVXMppbXBPiXS"
      role: admin  
      workspaces:
        - workspace
```
Result: OK

```
➜  epinio git:(main) epinio login -u 11111 https://epinio.172.19.0.3.omg.howdoi.website

🚢  Login to your Epinio cluster [https://epinio.172.19.0.3.omg.howdoi.website]
Password: 

⚠️  Certificate signed by unknown authority

|     KEY     |      VALUE      |
|-------------|-----------------|
| Issuer Name | CN=epinio-ca    |
| Common Name | epinio-ca       |
| Expiry      | 2023-January-16 |

Do you want to trust it (y/n): y

✔️  Trusting certificate for address https://epinio.172.19.0.3.omg.howdoi.website...
✔️  Login successful
➜  epinio git:(main) epinio login -u "11111" https://epinio.172.19.0.3.omg.howdoi.website
🚢  Login to your Epinio cluster [https://epinio.172.19.0.3.omg.howdoi.website]
Password: 

⚠️  Certificate signed by unknown authority

|     KEY     |      VALUE      |
|-------------|-----------------|
| Issuer Name | CN=epinio-ca    |
| Common Name | epinio-ca       |
| Expiry      | 2023-January-16 |

Do you want to trust it (y/n): y

✔️  Trusting certificate for address https://epinio.172.19.0.3.omg.howdoi.website...
✔️  Login successful
```

---

I also checked these 2 scenarios. I am not sure they directly apply here, but here it is the outcome in case we need to spin separate tickets: 

**Scenario 2: Login in UI with "11111" and 11111 with username `"11111"`** 
Result: Success for number without quotes `11111` Failed for `"11111"`
![image](https://user-images.githubusercontent.com/37271841/196350544-f41c8af2-5781-4c12-a96a-203110e367a3.png)


**Scenario 3: Login in CLI with "11111" and 11111 with username with numbers without quotes `11111`** 

```yaml
users:
    - username: admin
      passwordBcrypt: "$2a$10$6bCi5NMstMK781In7JGiL.B44pgoplUb330FQvm6mVXMppbXBPiXS"
      role: admin
    - username: epinio
      passwordBcrypt: "$2a$10$6bCi5NMstMK781In7JGiL.B44pgoplUb330FQvm6mVXMppbXBPiXS"
      role: user
    - username: 11111
      passwordBcrypt: "$2a$10$6bCi5NMstMK781In7JGiL.B44pgoplUb330FQvm6mVXMppbXBPiXS"
      role: admin  
      workspaces:
        - workspace
```
Result: Failed to process yaml file
```
INFO[0004] Successfully imported 1 image(s) into 1 cluster(s) 
Release "epinio" does not exist. Installing it now.
Error: values don't meet the specifications of the schema(s) in the following chart(s):
epinio:
- api.users.3.username: Invalid type. Expected: string, given: integer

make: *** [Makefile:191: prepare_environment_k3d] Error 1
```

**Comment by enrichman** [comment]
@mmartin24 that is correct. For scenario 2 you are trying to login with a user that doesn't exists (user: `"11111"`, while the existing user is the `11111`). The quotes inside the manifest are used only to escape the digits.

You can quote also `"admin"` but you should still login with `admin`.

If you want to login with a `"11111"` user, you should probably have:

```yaml
users:
    - username: '"11111"'
      passwordBcrypt: "$2a$10$6bCi5NMstMK781In7JGiL.B44pgoplUb330FQvm6mVXMppbXBPiXS"
      role: admin  
      workspaces:
        - workspace
```

or
```yaml
users:
    - username: "\"11111\""
      passwordBcrypt: "$2a$10$6bCi5NMstMK781In7JGiL.B44pgoplUb330FQvm6mVXMppbXBPiXS"
      role: admin  
      workspaces:
        - workspace
```

For scenario 3 it's actually the bug that we have and that was fixed: 

https://github.com/epinio/helm-charts/pull/289/files#diff-d0a1d5ae86284ae9e2dca9e9abeedd5568d09f520a00582bc02ea626ef3ee64bR13-R14

We are now quoting the username, so if you remove the quotes you are actually reintroducing the bug.
