### ISSUE TITLE
Test roles based on incoming Claims

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio#1877]
Test related issue: https://github.com/epinio/epinio/issues/1816

**Comment by mmartin24** [comment]
Tested as follows using Github connector and epinio as org:

### 1 - Get the config.yaml from dex-config secret and store it as a file
```
kubectl get secrets/dex-config -n epinio -o=go-template='{{index .data "config.yaml" | base64decode }}' > config.yaml
```

### 2 - Ensure Dex-Github connector is ready (more info [here](https://dexidp.io/docs/connectors/github/)). Add modifications needed in yaml file (Git connector)
```
connectors:
- type: github
  id: github  
  # Required field for connector name.
  name: github
  config:
    # Credentials can be string literals or pulled from the environment.
    clientID: 43948da77479f2de272c
    clientSecret: 52bd4cd11ba9f9e01ec13f7f147534f1c00278c3
    redirectURI: "https://auth.172.19.0.3.omg.howdoi.website/callback"
    loadAllGroups: true
    orgs:
    - name: epinio
```

### 3 - Patch the secret by using the modified config.yaml
```
data_base64=$(cat config.yaml | base64 | tr -d '\n')
kubectl patch secret dex-config -n epinio -p='{"data":{"config.yaml": "'$data_base64'"}}'
```

### 4 - Repeat something similar with roles Mapping key
```
data_base64=$(echo -n "\
  - connectorId: github
    groups:
    - id: epinio:qa
      role: admin
    - id: epinio:epinio
      role: user" | base64 | tr -d '\n')
```
```
kubectl patch secret dex-config -n epinio -p='{"data":{"rolesMapping": "'$data_base64'"}}'
```

### 5 - Restart Dex
```
kubectl delete pod -n epinio -l app.kubernetes.io/name=dex
```

### 6 - Login in Github
```
epinio login --oidc --trust-ca https://epinio.172.19.0.3.omg.howdoi.website
```

## Result. When we check secrets for the user we see how the role changes depending of the groups

Case 1: Group with admin roles
![role_admin](https://user-images.githubusercontent.com/37271841/203535172-f9d20e52-4f89-4931-ae82-2d85ef53ccee.png)

Case 2: Group with user roles
![role_user](https://user-images.githubusercontent.com/37271841/203535197-11d52266-d3fd-4a08-84b2-5475adb20467.png)
