### ISSUE TITLE
Exported container doesn't have `entrypoint` set and also `command` is missing in helm template

### ISSUE THREAD

**Issue by thehejik** [epinio/epinio#1892]
**Describe the bug**
After exporting an epinio app I tried to import the app by using exported helm chart and image. The resulting pod is in `CreateContainerError` state most probably due to missing entrypoint set in container manifest or/and missing command/args keys in deployment helm template for the app.

**To Reproduce**
```
$ epinio app export app-webui ./
$ docker image import ./app-image.tar thehejik/app-webui
$ docker push thehejik/app-webui
$ mkdir chart
$ tar xvf app-chart.tar.gz -C chart/
```
Modify values.yaml to use the `image` and modify the route `domain` and `id`:
```
epinio:
  appName: app-webui-helm
  configpaths: []
  configurations: []
  env: []
  imageURL: thehejik/app-webui
  ingress: null
  replicaCount: 1
  routes:
  - domain: app-webui-helm.10.100.103.16.omg.howdoi.website
	id: app-webui-helm.10.100.103.16.omg.howdoi.website
	path: /
  stageID: 55aea1b94d388043
  start: null
  tlsIssuer: epinio-ca
  username: admin
```
Deploy the app by using the helm chart and image:
```
helm upgrade --install app-chart-helm ./chart/epinio-application/ --values ./values.yaml
```

**Expected behavior**
the app pod is running 

**Logs**
from the `describe pod`:
```
Error: failed to generate container "dd2594df4d8c040042feafff171956e8ec32ab87adb728a9768efaa025c1bc0d" spec: failed to generate spec: no command specified
```
