### ISSUE TITLE
Issue connecting to an external AWS S3 storage

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#1895]
**Describe the bug**

I'm setting up Epinio on AWS using IAM instance roles to access AWS services, first for S3.

For testing, I have set up the AWS CLI on the worker nodes and added the s3: roles to the instance profile; access is ok:
```
ubuntu@rke-99738d-2:~/.aws$ aws s3 cp config s3://epinio-s3
upload: ./config to s3://epinio-s3/config                         
ubuntu@rke-99738d-2:~/.aws$ aws s3 ls s3://epinio-s3
2022-11-25 18:21:23        165 config
```

I've configured S3 in Epinio with the following values:

```
# Connection details for S3
s3:
  endpoint: [s3.amazonaws.com](http://s3.amazonaws.com/)
  bucket: "epinio-s3"
  region: "eu-central-1"
  useSSL: true
```

However, when I try to push an application, it fails with the following:
```
error pushing app to server: can't upload archive: server status code: Internal Server Error
{"errors":[{"status":500,"title":"ensuring bucket: checking bucket epinio-s3 exists: Access Denied.","details":"uploading the application sources blob
Server Backtrace: Access Denied.
checking bucket epinio-s3 exists\[ngithub.com/epinio/epinio/internal/s3manager.(*Manager).EnsureBucket](http://ngithub.com/epinio/epinio/internal/s3manager.(*Manager).EnsureBucket)
/home/runner/work/epinio/epinio/internal/s3manager/s3manager.go:241 ...
```

Is my thought process wrong? Shouldn't Epinio be able to access the S3 bucket through the IAM profile? Or would you like me to specify the ARN in the helm values somehow?

**Comment by chfrank-cgn** [comment]
Speaking with @thehejik it should be feasible to make Epinio AWS-Aware and add the ability to use the instance profile or IRSA (utilizing kubernetes service accounts for IAM). 

A config map for the AWS CLI pod could look like this:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-cli-config
  namespace: epinio
data:
  config: |

    [default]
    region=eu-central-1
    output=json

    [profile]
    role_arn = arn:aws:iam::203620351803:role/rancher-combined-control-worker
    source_profile = Ec2InstanceMetadata
```

which would then be referenced by the AWS CLI pod:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: aws-s3-create
  namespace: epinio
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      containers:
        - name: aws-cli
          image: amazon/aws-cli
          command: ["aws", "s3", "mb", "s3://epinio-s3"]
          volumeMounts:
            - name: aws-cli-config
              mountPath: /root/.aws
      restartPolicy: Never
      volumes:
        - name: aws-cli-config
          configMap:
            name: aws-cli-config
```

What do you think?

**Comment by chfrank-cgn** [comment]
It might make sense to turn this into a general flag and also allow the same for ECR, wouldn't it?

```
apiVersion: batch/v1
kind: Job
metadata:
  name: aws-ecr-create
  namespace: epinio
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      containers:
        - name: aws-cli
          image: amazon/aws-cli
          command: ["aws", "ecr", "create-repository", "--repository-name", "epinio-ecr"]
          volumeMounts:
            - name: aws-cli-config
              mountPath: /root/.aws
      restartPolicy: Never
      volumes:
        - name: aws-cli-config
          configMap:
            name: aws-cli-config
```
