### ISSUE TITLE
How to install/config epinio so that it support custom domain

### ISSUE THREAD

**Issue by gitricko** [epinio/epinio#1975]
**Describe the bug**
For security purpose, logging and firewall purpose, it might be useful to have deployed apps having a domain that is different from the epinio's system domain.

For instance:

`epinio login https://epinio.internal.xxx.com`

For pushing apps, we shall use `epinio app push -n sample -p . --route myapp.yyy.com`

The question i have here is how do i install epinio (or update epinio) so that this is supported ? The only documentation i saw in epinio is: https://docs.epinio.io/next/howtos/custom_routes

`
Epinio will try to create a TLS certificate for any defined route, like it does for the wildcard system domain ones. Depending on the issuer that is being used, DNS may have to work before the domain can be used. In other words, the domain must resolve to the cluster's Ingress IP. Read more about the issuers here: [Certificate Issuers](https://docs.epinio.io/next/howtos/certificate_issuers)
`
Wonder if we can have more prescriptive or more direct example on how we do this.

cc @enrichman

**Comment by gitricko** [comment]
Just did some test with the hint of: `the domain must resolve to the cluster's Ingress IP`.

I install epinio with system domain of `127.0.0.1.sslip.io`

And i push the app with
`epinio app push -n sample -p . --route myapp.127.0.0.1.omg.howdoi.website`

And i was able to address the app though it is a self-signcert.

This mean, all i need to do is to figure how to configure cert-manager component in epinio...

@riqueps @pedro-brito-ilia

**Comment by riqueps** [comment]
> Just did some test with the hint of: `the domain must resolve to the cluster's Ingress IP`.
> 
> I install epinio with system domain of `127.0.0.1.sslip.io`
> 
> And i push the app with `epinio app push -n sample -p . --route myapp.127.0.0.1.omg.howdoi.website`
> 
> And i was able to address the app though it is a self-signcert.
> 
> This mean, all i need to do is to figure how to configure cert-manager component in epinio...
> 
> @riqueps @pedro-brito-ilia

Reading the documentation, I believe is just needed to add an extra DNS section on cluster Issuer manifest file.
Eg:
```
...
    solvers:
    - selector:
        dnsZones:
          - "xxxx.com"
      dns01:
        route53:
          region: aws_region
          hostedZoneID: hosted_zone_id
         role: aws_role
    - selector:
        dnsZones:
          - "yyyy.com"
      dns02:
        route53:
          region: aws_region
          hostedZoneID: hosted_zone_id
         role: aws_role
```

**Comment by riqueps** [comment]
It worked.

Details:
- I installed epinio with system domain of `domain1.com`
- Add an extra DNS section on the Cluster Issuer as following:
```   
    solvers:
    - dns01:
        route53:
          hostedZoneID: hosted_zone_id_1
          region: aws_region
          role: arn:aws:iam::XXXXXXX:role/CertManager
      selector:
        dnsZones:
        - domain1.com
    - dns01:
        route53:
          hostedZoneID: hosted_zone_id_2
          region: aws_region
          role: arn:aws:iam::XXXXXXX:role:role/CertManager
      selector:
        dnsZones:
        - domain2.com
```
- Push an app with: `epinio app push -n sample -p . --route myapp.domain2.com`
