### ISSUE TITLE
Add OCI-based registries support for Custom Services

### ISSUE THREAD

**Issue by riqueps** [epinio/epinio#2096]
**Is your feature request related to a problem? Please describe.**
Be able to deploy custom services helm-charts, which are stored on a OCI-based registries.

**Describe the solution you'd like**

```
apiVersion: application.epinio.io/v1
kind: Service
....
spec:
  ...
  helmRepo:
    name: aws-s3
    url: oci://AWS_ACCOUNT_ID.dkr.ecr.AWS_REGION.amazonaws.com
....
```

**Additional context**
I tested with [AWS ECR](https://docs.aws.amazon.com/AmazonECR/latest/userguide/push-oci-artifact.html), but I got the error bellow:

      ❌  error creating service: service create failed: Internal Server Error: error deploying service helm chart: creating the chart repository: object required

I'm able to deploy the same helm-chart from an Ec2 instance, using this command: `helm install s3-henrique-test-ecr oci://AWS_ACCOUNT_ID.dkr.ecr.AWS_REGION.amazonaws.com/aws-s3 --version x.x.x `

**Comment by agracey** [comment]
I believe that this is (or at least was) doable. If this has changed, then I think it's a regression.

**Comment by agracey** [comment]
I'd like to make sure that this is the case for application template charts as well.

**Comment by agracey** [comment]
I never got a chance to test this but maybe this can help: https://github.com/epinio/epinio/issues/1485#issuecomment-1136892722

**Comment by agracey** [comment]
Try:
```
apiVersion: application.epinio.io/v1
kind: Service
....
spec:
  ...
  helmChart: oci://AWS_ACCOUNT_ID.dkr.ecr.AWS_REGION.amazonaws.com
  chartVersion: latest
....
```


For applications templates: https://github.com/epinio/epinio/blob/4659a797d79fd880522cc00464dbeede782cbac3/internal/helm/helm.go#L336 could stop the same functionality

**Comment by riqueps** [comment]
I got this error when trying to do `kubectl apply`

     error: error validating "s3-service-ecr.yaml": error validating data: ValidationError(Service.spec): unknown field "helmChart" in io.epinio.application.v1.Service.spec; if you choose to ignore these errors, turn validation off with --validate=false

Here is the full file:
```
apiVersion: application.epinio.io/v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: epinio
    meta.helm.sh/release-namespace: epinio
  generation: 2
  name: s3-dev-test
  namespace: epinio
spec:
  appVersion: 1.5.1
  helmChart: oci://AWS_ACCOUNT_ID.dkr.ecr.AWS_REGION.amazonaws.com/aws-s3
  chartVersion: 0.2.0
  description: |
    This service is going to deploy a simple default S3 bucket.
  #helmRepo:
  #  name: aws-s3
  #  url: oci://045889879690.dkr.ecr.us-east-1.amazonaws.com
  name: aws-s3
  serviceIcon: https://static-00.iconduck.com/assets.00/storage-amazons3-bucket-icon-495x512-rd519ixy.png
  shortDescription: A S3 service that can be used during development
  values: |-
```
