### ISSUE TITLE
Add boolean to know if a path comes from archive

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio#2213]
Outcome from UI demo.
The idea behind this is to use a boolean to know if path comes from archive in order not to rely in the extension.

**Comment by andreas-kupries** [comment]
Pretty sure that the UI wants more than a boolean.
IIRC I saw that they tracked the kind of archive, i.e. (zip, tar tar+gz, tar+bzip2, tar+xz, ...)

**Comment by enrichman** [comment]
Yes, not sure but we should rephrase this ticket with the need, and not the solution.

I.e.: we need something to distinguish the path from being a folder or an archive.

I think we just need to understand if the `path` is coming from an `archive` or `folder`, because they need this just to select the right choice from the dropdown. But we should not be tight too much to the UI anyway.

```yaml
origin:
  kind: "archive"
  path: "my-archive.tar.gz"
```

```yaml
origin:
  kind: "folder"
  path: "my-folder"
```

Probably I would not use the `kind` key to avoid any collision with what we have at the moment. Something like `source: [file|folder]` could work as well.
