### ISSUE TITLE
Investigate / Compare manifest file UI/CLI and resolve if any changes are needed

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio#2214]
The manifest from this app in the UI ([sample-app.tar.gz](https://github.com/epinio/epinio-end-to-end-tests/blob/main/cypress/fixtures/sample-app.tar.gz)) is different from the CLI:

### CLI (output yaml by default)
```
name: testapp
configuration:
  instances: 1
  environment:
    EPINIO_APP_DATA: '{"source":{"type":"archive","builderImage":"paketobuildpacks/builder:full","archive":{"fileName":"sample-app.tar.gz"}}}'
  routes:
  - testapp.192.168.16.3.omg.howdoi.website
  appchart: standard
origin:
  git:
    url: ""
  path: sample-app.tar.gz
namespace: workspace

````

### UI: (output json by default)

```
{
  "name": "testapp",
  "configuration": {
    "instances": 1,
    "configurations": [],
    "environment": {},
    "routes": [
      "testapp.192.168.16.3.omg.howdoi.website"
    ],
    "appchart": "standard"
  },
  "origin": {
    "Kind": 1,
    "git": {
      "repository": ""
    },
    "path": "/home/mmartin/suse/epinio-repos/epinio/assets/sample-app/"
  }
}

```

This ticket is to analyze these differences and if it could be potentially an issue when pushing from CLI to UI or viceversa

**Comment by enrichman** [comment]
I think we should make this as an **Epic** and address one by one all the needed changes.

First of all we should probably rewrite a bit this [page](https://docs.epinio.io/references/manifests#manifest-format) to explain better how to write a sample manifest file. I would put the small example right at the top, with some comments into it. We should add also a sample manifest in the `assets` folder, and a JSON schema that could be used to validate the YAML (/cc @olblak because he did the same with [updatecli](https://www.updatecli.io/))

As Andreas said we are not expecting the manifest to be a JSON and unexpected things could happen, so at the moment I would stick to a YAML format.

Looking at the manifest documentation it seems that we are already supporting the `builderImage`, but it's stored in the
```yaml
staging:
  builder: "builder-image"
```
section. So probably nothing to add there.

**Comment by mmartin24** [comment]
@andreas-kupries about this question from basic notes [above](https://github.com/epinio/epinio/issues/2214#issuecomment-1511217541) :
> * question Does the UI support the CLI yaml as input for a manifest ?

>> Yes. it does. You can upload a yaml in the UI from cli and will work. Just tried this and worked:
```
name: testapp
configuration:
  instances: 1
  environment:
    EPINIO_APP_DATA: '{"source":{"type":"archive","builderImage":"paketobuildpacks/builder:full","archive":{"fileName":"sample-app.tar.gz"}}}'
  routes:
  - testapp.192.168.16.3.omg.howdoi.website
  appchart: standard
origin:
  git:
    url: ""
  path: sample-app.tar.gz
namespace: workspace
```

However, pls note that still we need to manually upload the source file
