### ISSUE TITLE
Service deployment with hooks are still waiting

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#2288]
Ref: https://github.com/epinio/epinio/pull/2136

**Describe the bug**
Trying to deploy a service containing a Helm hook will still apparently hang the CLI because of how Helm hooks work: https://helm.sh/docs/topics/charts_hooks/

There is a feature request on Helm on how they will address this, but still under development: https://github.com/helm/helm/issues/10555

We can think about doing the installation in background (goroutine?) without the client waiting.

**To Reproduce**
Try to deploy a service with an hanging Job/hook: https://github.com/enrichman/helm-charts/tree/main/charts/simplejob

```yaml
apiVersion: application.epinio.io/v1
kind: Service
metadata:
  name: simplejob
  namespace: {{ .Release.Namespace }}
spec:
  name: simplejob
  shortDescription: A simplejob
  description: |
    This simplejob
  chart: simplejob
  chartVersion: 0.0.1
  appVersion: 0.0.1
  helmRepo:
    name: enrichman
    url: https://enrichman.github.io/helm-charts
  values: |-
    {{- template "epinio.catalog-service-values" . }}
```

Installing this service will wait for the Job completion.

**Expected behavior**
Without the `--wait` flag I'm expecting the CLI to exit immediately without waiting for the service deployment.
