### ISSUE TITLE
Support Private Helm repositories

### ISSUE THREAD

**Issue by riqueps** [epinio/epinio#2303]
**Is your feature request related to a problem? Please describe.**
Currently we are developing integrations with cloud native services (eg: gcp cloud storage, gcp cloud database...), in order to have these services available on epinio service catalog.

As these helm-charts can contain some private data, we must use private helm repositories.

**Describe the solution you'd like**
Make epinio support private helm repositories.

**Additional context**

- GKE standard v1.25.
- Epinio 1.8.0
- Using [GKE Workload Identity ](https://cloud.google.com/kubernetes-engine/docs/concepts/workload-identity#:~:text=Workload%20Identity%20allows%20a%20Kubernetes,when%20accessing%20Google%20Cloud%20APIs)

Even setting up the epinio-server ServiceAccount with Artifact Registry Reader permission, we receive an error when we set the Artifact Registry privately:
`❌  error creating service: service create failed: Internal Server Error: error deploying service helm chart: failed to authorize: failed to fetch anonymous token: unexpected status: 403 Forbidden`

To allow helm pull chart from private repo, we must run `helm registry login` before try to install it.
Here is the options available for helm login on[ GCP Artifact Registry](https://cloud.google.com/artifact-registry/docs/helm/authentication)

**To reproduce**
- Store a helm-chart on a private repo
- Add the service on epinio catalog
- Try to create the service (epinio service create....)

**Comment by riqueps** [comment]
Looking at the helm-client (https://github.com/mittwald/go-helm-client), it already supports private helm-charts.

As a suggestion, one possible solution can be add a new parameter on the epinio service definition (secret) where it points to a k8s secret.
```
apiVersion: application.epinio.io/v1
kind: Service
....
spec:
  ....
  helmRepo:
    name: orbit-service-chart
    url: https://orbit-service-chart.s3.amazonaws.com
    secret: K8S_SECRET_NAME
 ...
```
