### ISSUE TITLE
[CLI] Update `branch` field for Git manifests in  CLI as in  UI to allow its correct upload

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio#2360]
## Issue
Related issue: https://github.com/epinio/ui/issues/227#issuecomment-1573958190
Need to update cli to match UI when uploading a manifest from cli. The issue can be observed when  using Gitlab source type with missing field ` branch: main`

Example:

```yaml
name: testapp-gitlab-ui
configuration:
  instances: 1
  routes:
  - testapp-gitlab-ui.172.19.0.3.omg.howdoi.website
  appchart: standard
origin:
  git:
    revision: bb6883114668e9aed4964ed3f60bed3bc623c202
    url: https://gitlab.com/richard-cox/epinio-sample-app
    provider: gitlab
    branch: main
staging:
  builder: paketobuildpacks/builder:full
namespace: workspace
```

![Image](https://github.com/epinio/epinio/assets/37271841/35f67f84-1cc0-402c-afb8-0ecf8251aef5)

# Testing steps

- Deploy gitlab app:
```
epinio push --name testatpp-gitlab-cli-2 --git-provider gitlab --git https://gitlab.com/richard-cox/epinio-sample-app,bb6883114668e9aed4964ed3f60bed3bc623c202
```
- Download manifest:
```
epinio app manifest testatpp-gitlab-cli-2 ~/Downloads/testapp-gitlab-cli.yml
```
- Try to import that manifest in the UI and observed how it is not possible (probably because the field `branch: main` is missing)
