### ISSUE TITLE
s3gw install on rancher failing again due to `.Values.defaultUserCredentialSecret`

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio#2451]
## Issue
Rancher tests have been failing since 07/10/23 during s3gw installation due to missing `.Values.defaultUserCredentialSecret`. [Example](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/5503532736/jobs/10028867743#step:3:115)

Error:
```

Filter
Disconnected
helm install --namespace=epinio --timeout=10m0s --values=/home/shell/helm/values-epinio-1.9.0-rc3.yaml --version=1.9.0-rc3 --wait=true epinio-install /home/shell/helm/epinio-1.9.0-rc3.tgz
creating 1 resource(s)
creating 1 resource(s)
creating 1 resource(s)
beginning wait for 3 resources with timeout of 1m0s
Error: INSTALLATION FAILED: execution error at (epinio/charts/s3gw/templates/chart-validation.yaml:10:4): Please provide a secret name for `.Values.defaultUserCredentialSecret`
```

![Image](https://user-images.githubusercontent.com/37271841/252893700-7f00a78d-dd26-44ed-affd-d997827f0771.png)

## To reproduce:
- Install Rancher (quick install can be done from epinio repo by running:
```
 make acceptance-cluster-delete && make acceptance-cluster-setup && export KUBECONFIG=$PWD/tmp/acceptance-kubeconfig && make install-cert-manager && make install-rancher
```
- Once logged in, go to preferences and select: "Include pre-release versions"
- Add epinio repo to get latest chart: `https://github.com/epinio/helm-charts`, branch `main`
- Install new fetched chart (currently 1.9.0-rc3)
- Create namespace `epinio`, name: `epinio-repo`
- Add Domain being used
- Select s3 storage > Install s3gw > Install
![Image](https://user-images.githubusercontent.com/37271841/252893975-21719e20-0afd-473b-afd4-bb5cd28ba65f.png)

## Observed behavior
App cannot be deployed and the mentioned error is displayed

## Notes
Pasting here values file:
```yaml
api:
  users:
    - passwordBcrypt: $2a$10$6bCi5NMstMK781In7JGiL.B44pgoplUb330FQvm6mVXMppbXBPiXS
      role: admin
      username: admin
    - passwordBcrypt: $2a$10$6bCi5NMstMK781In7JGiL.B44pgoplUb330FQvm6mVXMppbXBPiXS
      role: user
      username: epinio
      workspaces:
        - workspace
appChart:
  default: >-
    https://github.com/epinio/helm-charts/releases/download/epinio-application-0.1.26/epinio-application-0.1.26.tgz
certManagerNamespace: cert-manager
containerregistry:
  certificateSecret: ''
  enabled: true
  image:
    nginx:
      repository: nginx
      tag: 1.23.2-alpine
    registry:
      repository: registry
      tag: 2.8.1
  imagePullPolicy: IfNotPresent
  ingressClassName: ''
dex:
  configSecret:
    create: false
    name: dex-config
  fullnameOverride: dex
  service:
    annotations: {}
  ui:
    redirectURI: ''
    secret: ''
email: epinio@suse.com
epinioUI:
  allowedOrigins: ''
  apiSkipSSL: 'true'
  apiURL: ''
  dexURL: ''
  enabled: true
  imagePullPolicy: IfNotPresent
  ingress:
    enabled: false
    ingressClassName: ''
  logLevel: info
  service:
    annotations: {}
  theme: light
  uiURL: ''
  wssURL: ''
global:
  cattle: {}
  dex:
    enabled: true
  domain: 172.19.0.3.omg.howdoi.website
  registryNamespace: apps
  registryPassword: changeme
  registryURL: ''
  registryUsername: admin
  tlsIssuer: epinio-ca
  tlsIssuerEmail: epinio@suse.com
image:
  awscli:
    repository: amazon/aws-cli
    tag: 2.9.14
  bash:
    registry: ghcr.io/
    repository: epinio/epinio-unpacker
    tag: ''
  builder:
    repository: paketobuildpacks/builder
    tag: full
  epinio:
    registry: ghcr.io/
    repository: epinio/epinio-server
    tag: ''
  epinio-ui:
    registry: ghcr.io/
    repository: epinio/epinio-ui
    tag: v1.9.0-0.0.1
  kubectl:
    repository: rancher/kubectl
    tag: v1.22.6
  skopeo:
    registry: quay.io/
    repository: skopeo/stable
    tag: v1.10
ingress:
  annotations: {}
  ingressClassName: ''
  nginxSSLRedirect: 'true'
kubed:
  enableAnalytics: false
  enabled: true
  fullnameOverride: kubed
minio:
  drivesPerNode: 4
  enabled: false
  existingSecret: minio-creds
  fullnameOverride: minio
  makeUserJob:
    podAnnotations:
      linkerd.io/inject: disabled
  persistence:
    size: 2Gi
  replicas: 1
  resources:
    requests:
      memory: 1Gi
  tls:
    certSecret: minio-tls
    enabled: true
    privateKey: tls.key
    publicCrt: tls.crt
s3:
  accessKeyID: ''
  bucket: epinio
  certificateSecret: ''
  endpoint: s3.amazonaws.com
  region: ''
  secretAccessKey: ''
  useSSL: true
s3gw:
  enabled: true
  ingress:
    enabled: false
  serviceName: s3gw
  storageClass:
    create: false
    name: ''
  storageSize: 2Gi
  ui:
    enabled: false
  useExistingSecret: true
server:
  accessControlAllowOrigin: ''
  disableTracking: false
  ingressClassName: ''
  stagingResourceRequests:
    cpu: ''
    memory: ''
  stagingServiceAccountName: ''
  timeoutMultiplier: 1
  traceLevel: 0
service:
  annotations: {}
serviceCatalog:
  enableDevServices: true
strategy:
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1
  type: RollingUpdate
useCustomTlsIssuer: false
```
