### ISSUE TITLE
Add support for git providers configuration

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#2488]
To be able to fetch sources from private repositories (#2236), skip the SSL verification (#2372), provide your own certificate or other options we need a way to configure the Git client.

A user should be able to provide a configuration for a git instance, and even for just a user/organization, or a single repository.

To do so we thought to use Kubernetes secrets to store these information, i.e.:

```yaml
apiVersion: v1 
kind: Secret 
type: Opaque 
metadata: 
  labels: 
    epinio.io/api-git-credentials: "true" 
  name: my-github-token 
  namespace: epinio 
stringData:
  url: https://github.com
  provider: github
  token: "abcde12345" 
  user: epinio 
  repo: helm-charts 
  skipSSL: true 
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIBaTCCAQ+gAwIBAgIRAN4tvwEOKogvOzT/KccL8t8wCgYIKoZIzj0EAwIwFDES
    ***************
    -----END CERTIFICATE-----
```

These information should be enough to configure the `go-git` client (see https://github.com/go-git/go-git/blob/36477e82f22623018ff170af8afc10c2c9bd50c5/options.go#L38C9-L38C9).

The only mandatory field should be the URL. This secret can be used just to configure the client, and so URL and the `skipSSL` are ok. Or just URL and `token` for example.

**Acceptance criteria** with some example scenarios:

When trying to access a private repo:
- it should fail when no config/token is provided
- it should succeed when right config is provided

When trying to access a self hosted with unsigned cert:
- it should fail if config has not the skipSSL value
- it should fail if config has not the correct cert value
- it should succeed if config has the skipSSL value
- it should succeed if config has the right certificate value

With multiple configuration/tokens we should check that the right one is used.
