### ISSUE TITLE
Test new Authorization roles

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio#2678]
Test new authorization roles implementation done in backend.

Ref: https://github.com/epinio/epinio/pull/2677

**Comment by mmartin24** [comment]
Tests done on branch `2631-new-authorization-roles`. The tests include indvidual config maps to be reproduced but they all are a tweaked version of the ones shipped directly from when installing directly from epinio repo. To do this install epinio directly from its main repo using: 
```
 make acceptance-cluster-delete && make acceptance-cluster-setup && export KUBECONFIG=$PWD/tmp/acceptance-kubeconfig && make install-cert-manager && make prepare_environment_k3d
```


#### Case 1 - Role `custom-role-1`is with `actions=namespace,app` can create namespaces and apps but not configurations
Preparation:
```yaml
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    epinio.io/role: "true"
  name: epinio-custom-role-1
  namespace: epinio
data:
  id: custom-role-1
  name: "My Custom Role 1"
  actions: |
    namespace
    app
EOF


# Secret prep
MY_USER=$(kubectl get secrets -n epinio -l 'epinio.io/api-user-credentials' | grep "ruser-epinio-" | awk '{print $1}')
kubectl annotate secret -n epinio --overwrite $MY_USER 'epinio.io/roles=custom-role-1'

# Restart pod:
kubectl delete pods -n epinio -l app.kubernetes.io/component=epinio-server
```

#### Tests:

- User should be able to apps and create namespaces:

```bash
epinio login -u epinio -p password --trust-ca https://epinio.192.168.16.3.omg.howdoi.website
epinio push --name jenkins-epinio --container-image-url jenkins/jenkins
epinio namespace create ns-epinio-1
epinio namespace list  
```

Expected output:
```
🚢  Listing namespaces

✔️  Epinio Namespaces:
|    NAME     |            CREATED            |  APPLICATIONS  | CONFIGURATIONS |
|-------------|-------------------------------|----------------|----------------|
| ns-epinio-1 | 2023-11-02 13:32:29 +0100 CET |                |                |
| workspace   | 2023-11-02 11:38:54 +0100 CET | jenkins-epinio |                |
```

- User should NOT be able to list or create configurations:

```bash
epinio configuration list
epinio configuration create config-1 foo bar
```

Expected output:
```
❌  error listing configurations: user unauthorized
❌  error creating configuration: user unauthorized
```
---


#### Case 2 - Role `admin` for any namespace, but scoped action `app_read` solely for namespace `ns-admin-appread-only`

Preparation:
```yaml
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    epinio.io/role: "true"
  name: epinio-custom-role-2
  namespace: epinio
data:
  id: custom-role-2
  name: "My Custom Role 2"
  actions: |
    app_read
EOF

# Create namespace before scoping it to it
epinio login -u admin -p password --trust-ca https://epinio.192.168.16.3.omg.howdoi.website
epinio namespace create ns-admin-appread-only
epinio target ns-admin-appread-only

# Secret prep
MY_USER=$(kubectl get secrets -n epinio -l 'epinio.io/api-user-credentials' | grep "ruser-admin-" | awk '{print $1}')
kubectl annotate secret -n epinio --overwrite $MY_USER 'epinio.io/roles=admin,custom-role-2:ns-admin-appread-only'


# Restart pod:
kubectl delete pods -n epinio -l app.kubernetes.io/component=epinio-server
```

#### Tests:

- User should be allowed to list an app: 

```bash
epinio app list
```

Expected output:
```
🚢  Listing applications
Namespace: ns-admin-appread-only

✔️  Epinio Applications:
| NAME | CREATED | STATUS | ROUTES | CONFIGURATIONS | STATUS DETAILS |
|------|---------|--------|--------|----------------|----------------|
```

- User should NOT be able to push an app or list a configuration:

```bash
epinio push --name jenkins-admin-1 --container-image-url jenkins/jenkins
epinio configuration list   
```

Expected output:
```
❌  error pushing app to server: user unauthorized
❌  error listing configurations: user unauthorized
```
---


#### Case 3 - Check an user without `app push` permission cannot use dependant `app_logs` action

Preparation:
```yaml
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    epinio.io/role: "true"
  name: epinio-user-role
  namespace: epinio
data:
  id: user
  name: "Epinio User Role"
  default: "true"
  actions: |
    namespace
    app_read
    configuration_read
    service_read
    gitconfig_read
    export_registries_read
EOF

# Secret prep
MY_USER=$(kubectl get secrets -n epinio -l 'epinio.io/api-user-credentials' | grep "ruser-epinio-" | awk '{print $1}')
kubectl annotate secret -n epinio --overwrite $MY_USER 'epinio.io/roles=user'


# Restart pod:
kubectl delete pods -n epinio -l app.kubernetes.io/component=epinio-server

# Login as admin to push an app in shared namespace workspace:
epinio login -u admin -p password --trust-ca https://epinio.192.168.16.3.omg.howdoi.website
epinio push --name jenkins-admin-1 --container-image-url jenkins/jenkins 

```


#### Tests:

- User should be allowed to: see the app "jenkins-admin-1" when login as epinio user 

```bash
epinio login -u epinio -p password --trust-ca https://epinio.192.168.16.3.omg.howdoi.website
epinio app list  

```

Expected output:
```
🚢  Listing applications
Namespace: workspace

✔️  Epinio Applications:
|      NAME       |            CREATED            | STATUS |                     ROUTES                      | CONFIGURATIONS | STATUS DETAILS |
|-----------------|-------------------------------|--------|-------------------------------------------------|----------------|----------------|
| jenkins-admin-1 | 2023-11-03 07:37:52 +0100 CET | 1/1    | jenkins-admin-1.192.168.16.3.omg.howdoi.website |                |                |
```

- User should NOT be able to: use app logs or push apps

```bash
epinio push --name jenkins-epinio-1 --container-image-url jenkins/jenkins  
epinio app logs jenkins-admin-1 

```

Expected output:
```
❌  error pushing app to server: user unauthorized
❌  error streaming application logs: user unauthorized
```
---

#### Case 4 - Check that OIDC user `epinio@epinio.io` with user role can initially create namespace and push app and then when scoped to user role within namespace `ns-1` cannot push anymore. 

Preparation:
```yaml
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    epinio.io/role: "true"
  name: epinio-user-role
  namespace: epinio
data:
  id: user
  name: "Epinio User Role"
  default: "true"
  actions: |
    namespace
    app_read
    configuration_read
    service_read
    gitconfig_read
    export_registries_read
EOF

# Login as user OIDC, create a namespace ns-1, target it and push an app
epinio login --oidc --trust-ca https://epinio.192.168.16.3.omg.howdoi.website
# Use: -u epinio@epinio.io -p password on OIDC UI
epinio namespace create ns-1
epinio target ns-1
epinio push --name jenkins-epinio-oidc-1 --container-image-url jenkins/jenkins 


# Secret prep
MY_USER=$(kubectl get secrets -n epinio -l 'epinio.io/api-user-credentials' | grep "ruser-epinioepinioio-" | awk '{print $1}')
kubectl annotate secret -n epinio --overwrite $MY_USER 'epinio.io/roles=user,user:ns-1'


# Restart pod:
kubectl delete pods -n epinio -l app.kubernetes.io/component=epinio-server
```

#### Tests:

- User should be allowed to: list apps and configs 

```bash

epinio app list  
epinio configuration list      
```

Expected output:
```

🚢  Listing applications
Namespace: ns-1

✔️  Epinio Applications:
|         NAME          |            CREATED            | STATUS |                        ROUTES                         | CONFIGURATIONS | STATUS DETAILS |
|-----------------------|-------------------------------|--------|-------------------------------------------------------|----------------|----------------|
| jenkins-epinio-oidc-1 | 2023-11-03 08:18:47 +0100 CET | 1/1    | jenkins-epinio-oidc-1.192.168.16.3.omg.howdoi.website |                |                |

🚢  Listing configurations
Namespace: ns-1

✔️  Epinio Configurations:
| NAME | CREATED | TYPE | ORIGIN | APPLICATIONS |
|------|---------|------|--------|--------------|
```

- User should NOT be able to : push apps anymore

```bash
epinio push --name jenkins-epinio-oidc-2 --container-image-url jenkins/jenkins   
```

Expected output:
```
❌  error pushing app to server: user unauthorized
```
---

#### Case 5 - Check that a role with no actions (blank user) cannot perform any operation

Preparation:
```yaml
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    epinio.io/role: "true"
  name: "epinio-blank-role"
  namespace: epinio
data:
  id: blank
  name: "Epinio Blank Role (no permissions)"
EOF

# Secret prep
MY_USER=$(kubectl get secrets -n epinio -l 'epinio.io/api-user-credentials' | grep "ruser-epinio-" | awk '{print $1}')
kubectl annotate secret -n epinio --overwrite $MY_USER 'epinio.io/roles=blank'


# Restart pod:
kubectl delete pods -n epinio -l app.kubernetes.io/component=epinio-server
```

### Tests:

- User should be allowed to login

```bash
epinio login -u epinio -p password --trust-ca https://epinio.192.168.16.3.omg.howdoi.website

```

Expected output:
```
✔️  Login successful
```

- User should NOT be able to: list namespaces, apps nor create them

```bash
epinio namespace create ns-1
epinio app create app-1
```

Expected output:
```
❌  error creating epinio-controlled namespace: user unauthorized
❌  error creating app: user unauthorized
```
---
