### ISSUE TITLE
Same username should not be possible to be assigned

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio#2692]
# Issue
It is possible to create 2 or more users with the same username. Login (and possibly all the other APIs) are not deterministic.

# To reproduce

- Create two users with different metadata name but same `username`

```yaml
cat <<EOF | kubectl apply -f -                                                              
apiVersion: v1
kind: Secret
type: BasicAuth
metadata:
  labels:
    epinio.io/api-user-credentials: "true"
    epinio.io/role: "admin"
  name: my-epinio-user-admin
  namespace: epinio
stringData:
  username: myuser
  namespaces: workspace
  password: "\$2a\$10\$6bCi5NMstMK781In7JGiL.B44pgoplUb330FQvm6mVXMppbXBPiXS"
EOF
```

```yaml
cat <<EOF | kubectl apply -f -                                                              
apiVersion: v1
kind: Secret
type: BasicAuth
metadata:
  labels:
    epinio.io/api-user-credentials: "true"
    epinio.io/role: "admin"
  name: my-epinio-user
  namespace: epinio
stringData:
  username: myuser
  namespaces: workspace
  password: "\$2a\$10\$6bCi5NMstMK781In7JGiL.B44pgoplUb330FQvm6mVXMppbXBPiXS"
EOF
```
- Go to secrets and decode `my-epinio-user-admin` and `my-epinio-user`

![Image](https://github.com/epinio/epinio/assets/37271841/b29f4358-5227-43d8-ad43-7a6809ee8696)
